In [2]:
# 1. Импортировать NumPy
import numpy as np

In [21]:
# 1.1 Создать массив 10 x 10 со случайными значениями от 1 до 100(int64)
a = np.random.randint(low=1, high=100, size=(10, 10), dtype=np.int64)
print(a)

# 1.2 найти среднее значение всех элементов массива
aMeanAll = np.mean(a)
print(aMeanAll)
# 1.3 найти среднее значение всех элементов для каждой строки   np.mean()
# и добавить как новый столбец
aMeanRow = np.mean(a, axis=1)
print(aMeanRow)
a = np.hstack((a, aMeanRow.reshape(10,-1)))
print(a)
# 1.4 найти сумму значение всех элементов для каждого столбца   np.sum()
# и добавить как новую строку, учитывая результат 1.3
aMeanCol = np.mean(a, axis=0)
print(aMeanCol)
a = np.vstack((a, aMeanCol))
print(a)

[[46 66 44 23 45  6 68 48 71 51]
 [33 44 35 92 63 80 94 20 64 56]
 [94 31 26 60 32 79 66 94 42  7]
 [ 2 77 90  7 74 97 91 39 84 15]
 [14 44 29 26  1 53 96 80 47  5]
 [74 98 47 13 68 48 99 52 39 99]
 [41 27 30 47 24 64 90 35 40 46]
 [ 1 56  7 16 62 12 27 78 80 47]
 [62 16 95  8 11 33 29 39  9 61]
 [33 43 62 50 87 47 99 75 76 96]]
50.49
[46.8 58.1 53.1 57.6 39.5 63.7 44.4 38.6 36.3 66.8]
[[46.  66.  44.  23.  45.   6.  68.  48.  71.  51.  46.8]
 [33.  44.  35.  92.  63.  80.  94.  20.  64.  56.  58.1]
 [94.  31.  26.  60.  32.  79.  66.  94.  42.   7.  53.1]
 [ 2.  77.  90.   7.  74.  97.  91.  39.  84.  15.  57.6]
 [14.  44.  29.  26.   1.  53.  96.  80.  47.   5.  39.5]
 [74.  98.  47.  13.  68.  48.  99.  52.  39.  99.  63.7]
 [41.  27.  30.  47.  24.  64.  90.  35.  40.  46.  44.4]
 [ 1.  56.   7.  16.  62.  12.  27.  78.  80.  47.  38.6]
 [62.  16.  95.   8.  11.  33.  29.  39.   9.  61.  36.3]
 [33.  43.  62.  50.  87.  47.  99.  75.  76.  96.  66.8]]
[40.   50.2  46.5  34.2  46.7 

In [33]:
# 2. Создать матрицу 7x7 с значениями 1,2,3,4,5,6,7 по главной диагонали, остальные нули.
a = np.eye(7)*np.arange(1,8)
print(a)

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0. 0. 0.]
 [0. 0. 3. 0. 0. 0. 0.]
 [0. 0. 0. 4. 0. 0. 0.]
 [0. 0. 0. 0. 5. 0. 0.]
 [0. 0. 0. 0. 0. 6. 0.]
 [0. 0. 0. 0. 0. 0. 7.]]


In [39]:
# 3. Создать случайную матрицу 5x7 целых чисел от 1 до 100 и поменять местами 3 и 5 колонки
a=np.random.randint(low=1, high=100, size=(5, 7), dtype=np.int64)
print(a)
a[:, 2], a[:, 4] = a[:, 4], a[:, 2].copy()
print(a)

[18 45 39 73 51]
[[88  3 62 93 18 20 59]
 [97 38 59 34 45 61 22]
 [29 80 67 16 39 93 15]
 [56 44 33  7 73 68 32]
 [33 82 23 25 51 89 26]]
