In [22]:
import numpy as np

__Задача 1__

Напишите функцию, которая находит сумму четных элементов на главной 
диагонали квадратной матрицы (именно чётных элементов, а не элементов на чётных позициях!). 
Если чётных элементов нет, то вывести 0

__Задача 2__

Решить задачи при условии, что массив может быть любой размерности:

2.1 Заменить максимальный элемент массива на 1000. (Повторяющихся максимальных элементов нет)    
2.2 Заменить минимальный элемент массива на 0. (Повторяющиеся минимальные элементы есть, поэтому нужно заменить все)

In [23]:
#__Задача 1__
a = np.random.randint(10, size=(4,4))
d = np.diagonal(a)
print(a)
sum_even = d[d % 2 == 0].sum()
sum_even

[[2 9 5 3]
 [6 0 5 6]
 [0 9 6 6]
 [0 8 8 6]]


14

In [25]:
#__Задача2.1__
a[np.unravel_index(np.max(a), a.shape)] = 1000
a

array([[   2,    9,    5,    3],
       [   6,    0,    5,    6],
       [   0, 1000,    6,    6],
       [   0,    8,    8,    6]])

In [26]:
#__Задача2.2__
a[a == np.min(a)] = 0
a

array([[   2,    9,    5,    3],
       [   6,    0,    5,    6],
       [   0, 1000,    6,    6],
       [   0,    8,    8,    6]])