In [1]:
import numpy as np

### Стекинг(Stacking)

Function|Description
---|:---
vstack()|Функция соединяет массивы вертикально
row_stack()|Функция соединяет массивы вертикально
hstack()|Функция соединяет массивы горизонтально
dstack()|Функция соединяет массивы в глубину, используя третье измерение(ось)
column_stack()|Функция соединяет одномерные массивы как колонки в двумерном массиве
concatenate()|Функция соединяет список или кортеж массивов

In [2]:
a = np.arange(9).reshape(3, 3); a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
b = 2 * a; b

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [5]:
np.hstack((a, b)) # объединяем по горизонтали, аргументы должны быть указаны в виде кортежа!

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [12]:
np.hstack((a, np.arange(100, 124).reshape(3, 8)))

array([[  0,   1,   2, 100, 101, 102, 103, 104, 105, 106, 107],
       [  3,   4,   5, 108, 109, 110, 111, 112, 113, 114, 115],
       [  6,   7,   8, 116, 117, 118, 119, 120, 121, 122, 123]])

In [10]:
np.hstack((a, a, b, b))

array([[ 0,  1,  2,  0,  1,  2,  0,  2,  4,  0,  2,  4],
       [ 3,  4,  5,  3,  4,  5,  6,  8, 10,  6,  8, 10],
       [ 6,  7,  8,  6,  7,  8, 12, 14, 16, 12, 14, 16]])

In [13]:
# Та же самая операция
# Строки - это axis(ось)=0, столбцы - это axis(ось)=1
np.concatenate((a, b), axis=1)

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [14]:
np.vstack((a, np.arange(100, 124).reshape(8, 3))) # по вертикали

array([[  0,   1,   2],
       [  3,   4,   5],
       [  6,   7,   8],
       [100, 101, 102],
       [103, 104, 105],
       [106, 107, 108],
       [109, 110, 111],
       [112, 113, 114],
       [115, 116, 117],
       [118, 119, 120],
       [121, 122, 123]])

In [16]:
np.vstack((a, b, a))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8]])

In [17]:
# Та же самая операция
np.concatenate((a, b), axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [18]:
a3d1 = np.arange(1, 25).reshape(2, 3, 4)
a3d1

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [19]:
a3d2 = np.arange(100, 136).reshape(3, 3, 4)
a3d2

array([[[100, 101, 102, 103],
        [104, 105, 106, 107],
        [108, 109, 110, 111]],

       [[112, 113, 114, 115],
        [116, 117, 118, 119],
        [120, 121, 122, 123]],

       [[124, 125, 126, 127],
        [128, 129, 130, 131],
        [132, 133, 134, 135]]])

In [20]:
res = np.vstack((a3d1, a3d2)); res

array([[[  1,   2,   3,   4],
        [  5,   6,   7,   8],
        [  9,  10,  11,  12]],

       [[ 13,  14,  15,  16],
        [ 17,  18,  19,  20],
        [ 21,  22,  23,  24]],

       [[100, 101, 102, 103],
        [104, 105, 106, 107],
        [108, 109, 110, 111]],

       [[112, 113, 114, 115],
        [116, 117, 118, 119],
        [120, 121, 122, 123]],

       [[124, 125, 126, 127],
        [128, 129, 130, 131],
        [132, 133, 134, 135]]])

In [21]:
res.shape

(5, 3, 4)

In [13]:
a, b

(array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]),
 array([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]]))

In [35]:
np.dstack((a, b))

array([[[ 0,  0],
        [ 1,  2],
        [ 2,  4]],

       [[ 3,  6],
        [ 4,  8],
        [ 5, 10]],

       [[ 6, 12],
        [ 7, 14],
        [ 8, 16]]])

In [32]:
c1 = np.arange(12).reshape(3, 4); c1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [33]:
c2 = np.arange(100, 112).reshape(3, 4); c2

array([[100, 101, 102, 103],
       [104, 105, 106, 107],
       [108, 109, 110, 111]])

In [15]:
np.dstack?

In [34]:
np.dstack((c1, c2)) # deep stack объединяем по глубине. Добавляем новое измерение

array([[[  0, 100],
        [  1, 101],
        [  2, 102],
        [  3, 103]],

       [[  4, 104],
        [  5, 105],
        [  6, 106],
        [  7, 107]],

       [[  8, 108],
        [  9, 109],
        [ 10, 110],
        [ 11, 111]]])

In [22]:
np.dstack((a3d1, a3d2))  # Error

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 3

In [36]:
np.row_stack((a, b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [37]:
np.row_stack((a, b)) == np.vstack((a, b))

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [38]:
a == b

array([[ True, False, False],
       [False, False, False],
       [False, False, False]])

In [41]:
res = a == b
type(res)

numpy.ndarray

In [76]:
## np.all вернет Тrue, если все элементы массива True
## np.any вернет Тrue, если хотя бы один элемент массива True
np.all(a == b), np.any(a == b)

(False, True)

In [44]:
np.all(np.row_stack((a, b)) == np.vstack((a, b)))

True

In [45]:
c = np.arange(2); c

array([0, 1])

In [46]:
twice_c = 2 * c; twice_c

array([0, 2])

In [47]:
np.column_stack((c, twice_c))

array([[0, 0],
       [1, 2]])

In [48]:
np.column_stack((a, b))

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [49]:
np.column_stack((a, b)) == np.hstack((a, b))

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

### Разделение(Splitting). hsplit(), vsplit(), dsplit(), split()

In [50]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [51]:
a2 = np.arange(1, 13).reshape(3, 4); a2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [52]:
# Разделяет на три массива по горизонтальной оси
res1, res2, res3 = np.hsplit(a, 3); res1.shape

(3, 1)

In [53]:
np.hsplit(a, 3)

[array([[0],
        [3],
        [6]]),
 array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]])]

In [57]:
# Разделяет на два массива по горизонтальной оси
np.hsplit(a2, 2)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12]])]

In [59]:
# np.hsplit(a1, 2) # Error

ValueError: array split does not result in an equal division

In [60]:
# то же самое, что и np.hsplit(a, 3)
np.split(a, 3, axis=1)

[array([[0],
        [3],
        [6]]),
 array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]])]

In [61]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [62]:
# Разделяет на три массива по вертикальной оси
np.vsplit(a, 3)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [63]:
a1, a2, a3 = np.vsplit(a, 3)

In [64]:
a1

array([[0, 1, 2]])

In [65]:
a1.shape

(1, 3)

In [66]:
# то же самое, что и np.vsplit(a, 3)
np.split(a, 3, axis=0)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [67]:
c = np.arange(27).reshape(3, 3, 3); c

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [68]:
np.dsplit(c, 3) ## С двумерными массивами выдаст ошибку

[array([[[ 0],
         [ 3],
         [ 6]],
 
        [[ 9],
         [12],
         [15]],
 
        [[18],
         [21],
         [24]]]),
 array([[[ 1],
         [ 4],
         [ 7]],
 
        [[10],
         [13],
         [16]],
 
        [[19],
         [22],
         [25]]]),
 array([[[ 2],
         [ 5],
         [ 8]],
 
        [[11],
         [14],
         [17]],
 
        [[20],
         [23],
         [26]]])]

In [69]:
c1, c2, c3 = np.dsplit(c, 3)

In [70]:
c1

array([[[ 0],
        [ 3],
        [ 6]],

       [[ 9],
        [12],
        [15]],

       [[18],
        [21],
        [24]]])

In [103]:
c1.shape

(3, 3, 1)

#### Деление на ноль

In [71]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [72]:
a / 0

C:\Users\Admin\AppData\Local\Temp/ipykernel_8344/1979898162.py:1: RuntimeWarning: divide by zero encountered in true_divide
  a / 0
C:\Users\Admin\AppData\Local\Temp/ipykernel_8344/1979898162.py:1: RuntimeWarning: invalid value encountered in true_divide
  a / 0


array([[nan, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [73]:
print(1 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))

nan
False
False
nan
True


In [53]:
id(np.nan)

1971371337648

#### Создание фиктивных осей

In [74]:
d = np.random.randn(6)
d

array([ 1.16239174, -0.60038364,  0.50365345, -0.1646603 , -0.2277854 ,
        0.26543633])

In [75]:
d.shape

(6,)

In [76]:
d.ndim

1

In [79]:
# Создание фиктивной оси
d1 = d[:, np.newaxis, None]
d1

array([[[ 1.16239174]],

       [[-0.60038364]],

       [[ 0.50365345]],

       [[-0.1646603 ]],

       [[-0.2277854 ]],

       [[ 0.26543633]]])

In [80]:
d1.ndim, d1.shape

(3, (6, 1, 1))

In [81]:
d2 = d[None, :, None]
d2.shape

(1, 6, 1)

In [82]:
d3 = d[None, None, :]
d3.shape

(1, 1, 6)

In [84]:
d3

array([[[ 1.16239174, -0.60038364,  0.50365345, -0.1646603 ,
         -0.2277854 ,  0.26543633]]])

In [85]:
m1 = np.ones((3, 4));m1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [86]:
m2 = np.ones((3, 5));m2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [87]:
m1_new = m1[np.newaxis, :, :]

In [88]:
m1_new.shape

(1, 3, 4)

In [89]:
m1_new

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [90]:
m1[:, :, None].shape # (3, 4, 1)
m1[:, :, None]

array([[[1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.]]])

In [91]:
m2[:, None, :]  # (3, 1, 5)

array([[[1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.]]])

### Broadcast

In [93]:
m3 = m1[:, :, None] + m2[:, None, :] # (3, 4, 1) + (3, 1, 5)
m3

array([[[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]],

       [[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]],

       [[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]]])

In [94]:
m3.shape

(3, 4, 5)

In [72]:
d

array([-1.78496987,  0.39277415,  0.96233008, -1.88256268, -0.27202006,
        0.3141703 ])

In [95]:
# Создать фиктивную ось для строк
d2 = np.expand_dims(d, axis=0)  
d2

array([[ 1.16239174, -0.60038364,  0.50365345, -0.1646603 , -0.2277854 ,
         0.26543633]])

In [96]:
d2.shape

(1, 6)

In [97]:
d.reshape(*d.shape, 1) # d[:, np.newaxis]

array([[ 1.16239174],
       [-0.60038364],
       [ 0.50365345],
       [-0.1646603 ],
       [-0.2277854 ],
       [ 0.26543633]])

In [98]:
d[:, np.newaxis, np.newaxis].shape

(6, 1, 1)

In [99]:
arr1 = np.full((3, 3), 2); arr1

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [100]:
arr2 = np.arange(10, 13); arr2

array([10, 11, 12])

In [101]:
arr2 = arr2[None, :]; arr2   # Фиктивная ось для строк

array([[10, 11, 12]])

In [102]:
arr1 + arr2

array([[12, 13, 14],
       [12, 13, 14],
       [12, 13, 14]])

In [103]:
arr3 = np.arange(10, 13)
arr3 = arr3[:, None]; arr3   # Фиктивная ось для столбцов

array([[10],
       [11],
       [12]])

In [144]:
arr1 + arr3

array([[12, 12, 12],
       [13, 13, 13],
       [14, 14, 14]])

In [104]:
ex1 = np.arange(24).reshape(2, 3, 4)
ex1

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [105]:
ex1 + np.arange(100, 102)[:, None, None]

array([[[100, 101, 102, 103],
        [104, 105, 106, 107],
        [108, 109, 110, 111]],

       [[113, 114, 115, 116],
        [117, 118, 119, 120],
        [121, 122, 123, 124]]])

In [106]:
## Параметр -1 автоматически пересчитывает нужную размерность
a = np.arange(32).reshape(-1, 4, 4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]]])

In [107]:
d1, d1.shape

(array([[[ 1.16239174]],
 
        [[-0.60038364]],
 
        [[ 0.50365345]],
 
        [[-0.1646603 ]],
 
        [[-0.2277854 ]],
 
        [[ 0.26543633]]]),
 (6, 1, 1))

In [108]:
# Удаляем фиктивные оси
new_d1 = np.squeeze(d1)
new_d1

array([ 1.16239174, -0.60038364,  0.50365345, -0.1646603 , -0.2277854 ,
        0.26543633])

## Операции между массивами и скалярами. 


In [ ]:
## Операции выполняются поэлементно

In [86]:
vec = np.arange(1, 7).reshape(2, 3)
vec

array([[1, 2, 3],
       [4, 5, 6]])

In [87]:
2 + vec

array([[3, 4, 5],
       [6, 7, 8]])

In [147]:
vec * vec

array([[ 1,  4,  9],
       [16, 25, 36]])

In [88]:
vec - vec

array([[0, 0, 0],
       [0, 0, 0]])

In [89]:
# Тип элементов при делении всегда float
1 / vec

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [90]:
a = vec ** 0.5
a

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

## Унарные операции
#### abs, fabs (для вещественных), sqrt, square, exp, log, log10, log2, sign, ceil, floor, rint, modf, isnan, isinf, cos, sin и т.д.

In [91]:
a

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [92]:
## Приводит значения вперед к ближайшему целому
np.ceil(a)

array([[1., 2., 2.],
       [2., 3., 3.]])

In [153]:
## Приводит значения назад к ближайшему целому
np.floor(a)

array([[1., 1., 1.],
       [2., 2., 2.]])

In [93]:
a_minus = -a
a_minus

array([[-1.        , -1.41421356, -1.73205081],
       [-2.        , -2.23606798, -2.44948974]])

In [94]:
np.ceil(a_minus)

array([[-1., -1., -1.],
       [-2., -2., -2.]])

In [95]:
np.floor(a_minus)

array([[-1., -2., -2.],
       [-2., -3., -3.]])

In [96]:
np.info(np.rint)

rint(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Round elements of the array to the nearest integer.

Parameters
----------
x : array_like
    Input array.
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``, locations within it where the condition is False will
    remain uninitialized.
**kwargs
    For other keyword

In [98]:
a

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [97]:
np.rint(a)

array([[1., 1., 2.],
       [2., 2., 2.]])

In [99]:
## _ - это результат выполнения последней ячейки
_.dtype

dtype('float64')

In [100]:
## - это результат выполнения предпоследней ячейки
__

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [101]:
## Результат - это два отдельных массива, целые и дробные части
np.modf(a)

(array([[0.        , 0.41421356, 0.73205081],
        [0.        , 0.23606798, 0.44948974]]),
 array([[1., 1., 1.],
        [2., 2., 2.]]))

In [102]:
res1, res2 = np.modf(a)
np.isnan(res1 / 0), np.isinf(res1 / 0)

C:\Users\Admin\AppData\Local\Temp/ipykernel_16096/3227368378.py:2: RuntimeWarning: divide by zero encountered in true_divide
  np.isnan(res1 / 0), np.isinf(res1 / 0)
C:\Users\Admin\AppData\Local\Temp/ipykernel_16096/3227368378.py:2: RuntimeWarning: invalid value encountered in true_divide
  np.isnan(res1 / 0), np.isinf(res1 / 0)


(array([[ True, False, False],
        [ True, False, False]]),
 array([[False,  True,  True],
        [False,  True,  True]]))

## Бинарные операции

In [103]:
k1 = np.arange(1,10).reshape(3,3)
k2 = np.arange(1, 4)
k1.shape, k2.shape

((3, 3), (3,))

In [104]:
k1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [105]:
k2

array([1, 2, 3])

In [106]:
k1 + k2

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [107]:
k1 * k2[:, None]

array([[ 1,  2,  3],
       [ 8, 10, 12],
       [21, 24, 27]])

In [108]:
k1 * k2[None, :]

array([[ 1,  4,  9],
       [ 4, 10, 18],
       [ 7, 16, 27]])

In [109]:
k3 = np.ones((3, 4))
k3.shape

(3, 4)

In [110]:
k3[np.newaxis, :, :]

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [111]:
k3[:, np.newaxis, :]

array([[[1., 1., 1., 1.]],

       [[1., 1., 1., 1.]],

       [[1., 1., 1., 1.]]])

In [112]:
k3[:, :, np.newaxis]

array([[[1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.]]])

In [113]:
k4 = np.arange(20).reshape(4, 5)
k4[np.newaxis, :, :]

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [114]:
v = np.arange(60).reshape((3, 4, 5))

In [115]:
v

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [172]:
v + k4[np.newaxis, :, :]

array([[[ 0,  2,  4,  6,  8],
        [10, 12, 14, 16, 18],
        [20, 22, 24, 26, 28],
        [30, 32, 34, 36, 38]],

       [[20, 22, 24, 26, 28],
        [30, 32, 34, 36, 38],
        [40, 42, 44, 46, 48],
        [50, 52, 54, 56, 58]],

       [[40, 42, 44, 46, 48],
        [50, 52, 54, 56, 58],
        [60, 62, 64, 66, 68],
        [70, 72, 74, 76, 78]]])

In [ ]:
# np.add(m1, m2) ->  +
# np.multiply(m1, m2) -> * 
# np.subtract(m1, m2) -> - 
# np.divide(m1, m2) -> /
# np.floor_divide(m1, m2), 
# np.power(m1, m2) -> **

In [116]:
mas_1 = np.array([[1, 2, 3], [20, 21, 22]]);mas_1

array([[ 1,  2,  3],
       [20, 21, 22]])

In [117]:
mas_2 = np.array([[5, 6, 7], [10, 11, 12]]); mas_2

array([[ 5,  6,  7],
       [10, 11, 12]])

In [118]:
# np.maximum(m1, m2) и np.minimum(m1,m2) - поэлементнo
np.maximum(mas_1, mas_2)

array([[ 5,  6,  7],
       [20, 21, 22]])

In [119]:
np.minimum(mas_1, mas_2)

array([[ 1,  2,  3],
       [10, 11, 12]])

In [122]:
np.fmax(mas_1, mas_2)

array([[ 5,  6,  7],
       [20, 21, 22]])

#### Операторы сравнения

In [ ]:
# np.maximum(m1, m2) и np.minimum(m1,m2) - поэлементнo, 
# np.fmax(m1, m2) и np.fmin(m1,m2) - игнорируют значение NaN 
# greater как a>, 
# greater_equal как >=, 
# less как <, 
# less_equal как <=, 
# equal как ==, 
# not_equal как !=

# logical_and как &, 
# logical_or как |, 
# logical_xor как ^
# !! операторы Python: and, or, not не поддерживаются

# broadcasting выполняется при двух условиях:
# 1.Либо размерности совпадают
# 2.Либо одна из размерностей равна 1

In [123]:
n = np.arange(4)
n1 = np.arange(4, 8).reshape(4, 1)
print(n)
print(n.shape)
print(n1)
print(n1.shape)

[0 1 2 3]
(4,)
[[4]
 [5]
 [6]
 [7]]
(4, 1)


In [182]:
np.add(n1, n)  # Неявно n приводится к размерности(1, 4)

array([[ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10]])

In [183]:
np.add(n, n1)

array([[ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10]])

In [124]:
m1 = np.arange(2,14).reshape(3, 4)
m1

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [125]:
m2 = np.arange(12).reshape(3, 4)
m2[0,0] = 1
m2[2,3] = 14
m2

array([[ 1,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 14]])

In [186]:
np.divide(m1, m2)

array([[2.        , 3.        , 2.        , 1.66666667],
       [1.5       , 1.4       , 1.33333333, 1.28571429],
       [1.25      , 1.22222222, 1.2       , 0.92857143]])

In [187]:
## Целочисленное деление
np.floor_divide(m1, m2)

array([[2, 3, 2, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 0]], dtype=int32)

In [126]:
#### Из каждой пары элементов выбирает наибольший
np.maximum(m1, m2)

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 14]])

In [127]:
np.minimum(m1, m2)

array([[ 1,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 13]])

In [128]:
np.power(m1, m2, dtype=np.int64)

array([[               2,                3,               16,
                     125],
       [            1296,            16807,           262144,
                 4782969],
       [       100000000,       2357947691,      61917364224,
        3937376385699289]], dtype=int64)

In [191]:
m1

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [192]:
m2

array([[ 1,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 14]])

In [131]:
m3 = np.arange(100, 103).reshape(3, 1)
m3

array([[100],
       [101],
       [102]])

In [137]:
m4 = m1.copy()
m4[0,3] = 101

In [138]:
m4 > m3  # broadcasting

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [139]:
m1 > m2

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True, False]])

In [140]:
m1 < m2

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True]])

In [195]:
## Логическое 'или' над двумя массивами
## True | False -> True; False | True -> True; True | True -> True; False | False -> False
(m1 > m2) | (m1 < m2)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [141]:
## Логическое 'и' над двумя массивами
## True | False -> False; False | True -> False; True | True -> True; False | False -> False
(m1 > m2) & (m1 < m2)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [142]:
m1 > m2

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True, False]])

In [143]:
## Инверсия(тильда)
~(m1 > m2)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True]])

In [144]:
~(m1 > m2) == (m2 > m1)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])