### Изменение размерности

In [1]:
import numpy as np

In [26]:
b = np.arange(24).reshape(2, 3, 4)
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

#### ravel() и reshape() изменяют сам массив, flatten() и resize() возвращют копию массива

In [27]:
# Результат - одномерный массив
b.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [28]:
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [29]:
b.flatten() ## возращает копию

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [30]:
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [31]:
print(b.shape)
b.shape = (6, 4)  ## то же самое, что и b.reshape(6, 4)

(2, 3, 4)


In [32]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [33]:
# Транспонирование матрицы: строки -> столбцы, столбцы -> строки
# можно и так b.T
b.transpose()

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

In [34]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [36]:
d = np.random.randint(1, 100, (2, 12))
d

array([[38, 71, 91, 66, 90, 59, 15, 90, 96, 71, 76, 34],
       [59, 61, 31, 18, 81,  9, 79, 58, 26, 44, 26, 39]])

In [37]:
# изменение размера массива
d.resize((3, 15), refcheck=False)
d

array([[38, 71, 91, 66, 90, 59, 15, 90, 96, 71, 76, 34, 59, 61, 31],
       [18, 81,  9, 79, 58, 26, 44, 26, 39,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0]])

In [43]:
c = np.arange(24)
c.shape = 8, 3

In [44]:
c.resize(9, 3)
c

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [ 0,  0,  0]])

In [45]:
c.resize?

In [46]:
## Новые элементы массива будут иметь значение 0
c1 = c.copy()
c1.resize(15, 3)
c1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0]])

In [47]:
## Новые элементы массива берут значения из старого массива
c2 = np.resize(c, (12, 3))
c2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [ 0,  0,  0],
       [ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8]])

### Добавление элементов

In [76]:
a = np.arange(10); a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
a = np.append(a, [1, 3, 4, 4]); a   ## Похож на метод extend для списка

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 3, 4, 4])

In [59]:
e = np.arange(12).reshape(3, 4)
e

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [60]:
e = np.append(e, [[99, 97, 96, 95]], axis=0)  # 0-я ось - это строки 2х мерном массиве
e

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [99, 97, 96, 95]])

In [61]:
e = np.append(e, [[99], [97], [96], [95]], axis=1) # 1-я ось - это столбцы 2х мерном массиве
e

array([[ 0,  1,  2,  3, 99],
       [ 4,  5,  6,  7, 97],
       [ 8,  9, 10, 11, 96],
       [99, 97, 96, 95, 95]])

In [62]:
temp = np.array([[99, 97, 96, 95]]); temp

array([[99, 97, 96, 95]])

In [31]:
temp.shape

(1, 4)

In [63]:
temp1 = np.array([[99], [97], [96], [95]]); temp1

array([[99],
       [97],
       [96],
       [95]])

In [64]:
temp1.shape

(4, 1)

In [65]:
a3d = np.arange(27).reshape(3, 3, 3); a3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [67]:
add_mas = np.arange(100, 109).reshape(1, 3, 3); add_mas

array([[[100, 101, 102],
        [103, 104, 105],
        [106, 107, 108]]])

In [68]:

a3d_new = np.append(a3d, add_mas, axis=0)   # 0-я ось - это глубина
a3d_new 

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8]],

       [[  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17]],

       [[ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26]],

       [[100, 101, 102],
        [103, 104, 105],
        [106, 107, 108]]])

In [69]:
vector = np.array([[4, 5, 6]])
vector, vector.shape

(array([[4, 5, 6]]), (1, 3))

In [70]:
foo = np.append(a3d_new, vector, 0); foo ## Error

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 3 dimension(s) and the array at index 1 has 2 dimension(s)

### Вставка элементов

In [77]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
# 2 - это индекс элемента, но не значение
# при вставке изменился тип элементов на тип массива
a = np.insert(a, 2, [99.1, 101.09]); a 

array([  0,   1,  99, 101,   2,   3,   4,   5,   6,   7,   8,   9])

In [79]:
# Вставка в массив NxM
a1 = np.array([[1, 1], [2, 2], [3, 3]])
a1

array([[1, 1],
       [2, 2],
       [3, 3]])

In [81]:
np.insert?

In [80]:
np.insert(a1, 1, 5)  # Сейчас массив будет представлен в виде единой ленточки(flatten)

array([1, 5, 1, 2, 2, 3, 3])

In [82]:
# Явно указали ось(измерение), по которой работаем(столбцы)
np.insert(a1, 1, 5, axis=1)

array([[1, 5, 1],
       [2, 5, 2],
       [3, 5, 3]])

In [83]:
a

array([  0,   1,  99, 101,   2,   3,   4,   5,   6,   7,   8,   9])

In [84]:
## Hовые элементы неявно будет преобразованы к типу элементов массива
a = np.insert(a, 6, np.random.randn(10) * 3)
a

array([  0,   1,  99, 101,   2,   3,   0,   0,   2,   2,   0,  -3,   0,
         2,   4,  -5,   4,   5,   6,   7,   8,   9])

In [85]:
a = np.random.randint(1, 20, (5, 3)); a

array([[16,  4,  6],
       [13,  5, 19],
       [ 6,  7, 15],
       [18,  8,  2],
       [ 1,  3,  6]])

In [86]:
np.delete(a, 3, axis=0)

array([[16,  4,  6],
       [13,  5, 19],
       [ 6,  7, 15],
       [ 1,  3,  6]])

In [87]:
np.delete(a, 2, axis=1)

array([[16,  4],
       [13,  5],
       [ 6,  7],
       [18,  8],
       [ 1,  3]])

#### ravel() и reshape() изменяют сам массив,  flatten() и resize() возвращют копию массива

#### Задача 1

In [ ]:
# Создать массив 10x10 со случайными значениями(int64), найти минимум и максимум.
# Вывести разницу между max и min для всего массива
# Вывести разницу между max и min для каждой оси

In [90]:
a = np.random.randint(1, 100, (3, 5))
a = a.astype(np.int64)
print(f"Массив:\n {a}")
print(f"Макс: {np.max(a)}, Мин:{np.min(a)}")
print(f"Разница всего массива: {np.max(a) - np.min(a)}")
print(f"Разница для каждой строки: {np.max(a, axis=1) - np.min(a, axis=1)}")    # axis=1 столбцы 
print(f"Разница для каждого столбца: {np.max(a, axis=0) - np.min(a, axis=0)}")  # axis=0 строки

Массив:
 [[ 9 14 10 71 58]
 [66 21 70 93 31]
 [15 82 86 58 99]]
Макс: 99, Мин:9
Разница всего массива: 90
Разница для каждой строки: [62 72 84]
Разница для каждого столбца: [57 68 76 35 68]


### Нужные параметры для вывода всех значений, а не только последнего(по умолчанию)

In [92]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"     ## Вывод всех строк без принтов
# InteractiveShell.ast_node_interactivity = "last"  ## Только последний вывод

In [93]:
arr = np.random.randint(0, 100, (10,10), dtype=np.int64)
arr
f'{np.max(arr) = }'
f'{np.min(arr) = }'
f'{np.max(arr) - np.min(arr) = }'
'-' * 20
f'{np.max(arr, axis=0) = }'
f'{np.min(arr, axis=0) = }'
f'{np.max(arr, axis=0) - np.min(arr, axis=0) = }'
'-'*20
f'{np.max(arr, axis=1) = }'
f'{np.min(arr, axis=1) = }'
f'{np.max(arr, axis=1) - np.min(arr, axis=1) = }'

array([[33, 24, 76, 55, 73, 81, 52, 20, 89, 68],
       [87, 95, 50, 40, 21,  1, 58, 23, 31, 25],
       [59, 64, 61, 55, 93,  0,  0, 63, 93, 86],
       [ 3, 12, 29,  2, 26, 22, 32, 48, 10, 46],
       [81, 75, 78, 91, 83, 56, 79, 44, 71, 44],
       [60, 92, 66, 97,  1,  4, 41, 79, 25, 16],
       [ 0, 16,  2, 41, 93, 83, 87, 85, 68, 87],
       [22, 25, 50, 78, 62, 67, 58, 26, 88, 40],
       [39, 51,  4,  5, 96,  5, 72, 60,  3, 92],
       [17, 33, 31, 85, 21, 81, 93, 61,  6, 47]], dtype=int64)

'np.max(arr) = 97'

'np.min(arr) = 0'

'np.max(arr) - np.min(arr) = 97'

'--------------------'

'np.max(arr, axis=0) = array([87, 95, 78, 97, 96, 83, 93, 85, 93, 92], dtype=int64)'

'np.min(arr, axis=0) = array([ 0, 12,  2,  2,  1,  0,  0, 20,  3, 16], dtype=int64)'

'np.max(arr, axis=0) - np.min(arr, axis=0) = array([87, 83, 76, 95, 95, 83, 93, 65, 90, 76], dtype=int64)'

'--------------------'

'np.max(arr, axis=1) = array([89, 95, 93, 48, 91, 97, 93, 88, 96, 93], dtype=int64)'

'np.min(arr, axis=1) = array([20,  1,  0,  2, 44,  1,  0, 22,  3,  6], dtype=int64)'

'np.max(arr, axis=1) - np.min(arr, axis=1) = array([69, 94, 93, 46, 47, 96, 93, 66, 93, 87], dtype=int64)'

In [94]:
np.random.seed(5)
a3d = np.random.randint(1, 50, (2, 3, 4))
a3d

array([[[36, 15, 48, 39],
        [17, 10,  9, 37],
        [40, 28, 49, 31]],

       [[17,  8, 13, 16],
        [40, 17, 28, 45],
        [14, 12,  2, 48]]])

In [97]:
np.min(a3d, axis=0) # по глубине

array([[17,  8, 13, 16],
       [17, 10,  9, 37],
       [14, 12,  2, 31]])

In [96]:
np.min(a3d, axis=1) # по строкам

array([[17, 10,  9, 31],
       [14,  8,  2, 16]])

In [100]:
np.min(a3d, axis=2) # по столбцам

array([[15,  9, 28],
       [ 8, 17,  2]])

In [107]:
res = np.min(a3d, axis=1) 
np.unravel_index(np.argmin(res), res.shape)

(1, 2)

In [102]:
np.min(np.min(a3d, axis=1), axis=0)

array([14,  8,  2, 16])

#### Задача 2 
np.random.seed(5)  
Матрица 4х3, со случайные целыми числами от 1 до 100  
1.1 найти столбец в котором разница между мин и макс минимальна и удалить его и остальные столбцы  


In [108]:
a3d

array([[[36, 15, 48, 39],
        [17, 10,  9, 37],
        [40, 28, 49, 31]],

       [[17,  8, 13, 16],
        [40, 17, 28, 45],
        [14, 12,  2, 48]]])

In [110]:
np.delete(a3d, 2, axis=2)

array([[[36, 15, 39],
        [17, 10, 37],
        [40, 28, 31]],

       [[17,  8, 16],
        [40, 17, 45],
        [14, 12, 48]]])

#### Решение 1.1 для 2d массива

In [127]:
np.random.seed(42)
arr = np.random.randint(1, 100, (4, 3))
arr

array([[52, 93, 15],
       [72, 61, 21],
       [83, 87, 75],
       [75, 88, 24]])

In [128]:
a = np.max(arr, axis=0) - np.min(arr, axis=0)
a

array([31, 32, 60])

In [129]:
idx = np.argmin(a)  # flat индекс минимального элемента
a[idx]

31

In [130]:
idx

0

In [131]:
new_arr = np.delete(arr, idx, axis=1); new_arr

array([[93, 15],
       [61, 21],
       [87, 75],
       [88, 24]])

In [133]:
# Тот же результат, но с помощью np.unravel_index()

index = np.unravel_index(np.argmin(a), a.shape)
new_arr_repeat = np.delete(arr, index[-1], axis=arr.ndim - 1)
new_arr_repeat


array([[93, 15],
       [61, 21],
       [87, 75],
       [88, 24]])

#### Решение 1.1 для 3d массива

In [141]:
np.random.seed(555)
a3d = np.random.randint(1, 100, (4, 3, 4)); a3d

array([[[27, 47, 34, 69],
        [39, 23, 54, 97],
        [85, 23, 87, 54]],

       [[75, 86, 28, 93],
        [59,  5, 66, 21],
        [52, 78, 84, 68]],

       [[20, 88, 57, 82],
        [ 5, 13, 66,  9],
        [21, 28, 30, 33]],

       [[48,  5, 21, 81],
        [80, 65, 51, 90],
        [93, 18, 14, 52]]])

In [137]:
diff = np.max(a3d, axis=1) - np.min(a3d, axis=1); diff

array([[58, 24, 53, 43],
       [23, 81, 56, 72],
       [16, 75, 36, 73],
       [45, 60, 37, 38]])

In [139]:
np.argmin(diff)  # flat индекс минимального элемента

8

In [140]:
index = np.unravel_index(np.argmin(diff), diff.shape); index

(2, 0)

In [138]:
new_a3d = np.delete(a3d, index[-1], axis=a3d.ndim - 1)
new_a3d

array([[[47, 34, 69],
        [23, 54, 97],
        [23, 87, 54]],

       [[86, 28, 93],
        [ 5, 66, 21],
        [78, 84, 68]],

       [[88, 57, 82],
        [13, 66,  9],
        [28, 30, 33]],

       [[ 5, 21, 81],
        [65, 51, 90],
        [18, 14, 52]]])