In [1]:
import numpy as np
import matplotlib.pyplot as plt

## Булево индексирование

In [2]:
colors = np.array(['Red', 'Green', 'Blue', 'Red', 'Blue', 'Green', 'Green'])
colors

array(['Red', 'Green', 'Blue', 'Red', 'Blue', 'Green', 'Green'],
      dtype='<U5')

In [3]:
colors.shape

(7,)

In [4]:
colors.dtype.name

'str160'

In [5]:
np.random.seed(0)  ## Фиксирует случайной выборки
data = np.random.randn(7, 4)
data

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788,  0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ,  0.14404357,  1.45427351],
       [ 0.76103773,  0.12167502,  0.44386323,  0.33367433],
       [ 1.49407907, -0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 , -0.74216502],
       [ 2.26975462, -1.45436567,  0.04575852, -0.18718385]])

In [6]:
colors

array(['Red', 'Green', 'Blue', 'Red', 'Blue', 'Green', 'Green'],
      dtype='<U5')

In [7]:
colors == 'Red'

array([ True, False, False,  True, False, False, False])

In [10]:
data[colors == 'Red']   # тоже самое, что и data[colors == 'Red', :]

array([[1.76405235, 0.40015721, 0.97873798, 2.2408932 ],
       [0.76103773, 0.12167502, 0.44386323, 0.33367433]])

In [11]:
data[[0, 3]]  ## Тот же результат, но явно указываем какие индексы брать для строк

array([[1.76405235, 0.40015721, 0.97873798, 2.2408932 ],
       [0.76103773, 0.12167502, 0.44386323, 0.33367433]])

In [12]:
## Применяем булево индексирование
data[(colors == 'Red') | (colors == 'Green')]   ## | это логическое "ИЛИ"

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788,  0.95008842, -0.15135721],
       [ 0.76103773,  0.12167502,  0.44386323,  0.33367433],
       [-2.55298982,  0.6536186 ,  0.8644362 , -0.74216502],
       [ 2.26975462, -1.45436567,  0.04575852, -0.18718385]])

In [14]:
## Применяем булево индексирование
data[(colors == 'Red') | (colors == 'Green'), :]   ## data[[0, 1, 3, 5, 6]]

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788,  0.95008842, -0.15135721],
       [ 0.76103773,  0.12167502,  0.44386323,  0.33367433],
       [-2.55298982,  0.6536186 ,  0.8644362 , -0.74216502],
       [ 2.26975462, -1.45436567,  0.04575852, -0.18718385]])

In [11]:
data[colors == 'Red', 2:]

array([[0.97873798, 2.2408932 ],
       [0.44386323, 0.33367433]])

In [12]:
data[colors == 'Red', 3]

array([2.2408932 , 0.33367433])

In [22]:
data

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788,  0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ,  0.14404357,  1.45427351],
       [ 0.76103773,  0.12167502,  0.44386323,  0.33367433],
       [ 1.49407907, -0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 , -0.74216502],
       [ 2.26975462, -1.45436567,  0.04575852, -0.18718385]])

In [30]:
# Здесь не 4 элемента, а 2
data[colors == 'Red', np.array([True, False, True, False])]

array([1.76405235, 0.44386323])

In [19]:
res = data[colors == 'Red']; res

array([[1.76405235, 0.40015721, 0.97873798, 2.2408932 ],
       [0.76103773, 0.12167502, 0.44386323, 0.33367433]])

In [20]:
res[:, np.array([False, False, True, True])]

array([[0.97873798, 2.2408932 ],
       [0.44386323, 0.33367433]])

In [12]:
data[colors == 'Red'][:, np.array([False, False, True, True])]

array([[0.97873798, 2.2408932 ],
       [0.44386323, 0.33367433]])

In [31]:
(colors != 'Red') 

array([False,  True,  True, False,  True,  True,  True])

In [32]:
data[colors != 'Red']

array([[ 1.86755799, -0.97727788,  0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ,  0.14404357,  1.45427351],
       [ 1.49407907, -0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 , -0.74216502],
       [ 2.26975462, -1.45436567,  0.04575852, -0.18718385]])

In [34]:
mask = (colors == 'Red') | (colors == 'Blue') # and и or не работают; &(и), |(или), ^(xor), ~(not)
mask  # array([ True, False,  True,  True,  True, False, False])

array([ True, False,  True,  True,  True, False, False])

In [35]:
mask.dtype

dtype('bool')

In [36]:
data[mask] # Всегда возвращается копия!

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [-0.10321885,  0.4105985 ,  0.14404357,  1.45427351],
       [ 0.76103773,  0.12167502,  0.44386323,  0.33367433],
       [ 1.49407907, -0.20515826,  0.3130677 , -0.85409574]])

In [37]:
data

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788,  0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ,  0.14404357,  1.45427351],
       [ 0.76103773,  0.12167502,  0.44386323,  0.33367433],
       [ 1.49407907, -0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 , -0.74216502],
       [ 2.26975462, -1.45436567,  0.04575852, -0.18718385]])

In [18]:
data > 0

array([[ True,  True,  True,  True],
       [ True, False,  True, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True, False,  True, False],
       [False,  True,  True, False],
       [ True, False,  True, False]])

In [19]:
data[data > 0]

array([1.76405235, 0.40015721, 0.97873798, 2.2408932 , 1.86755799,
       0.95008842, 0.4105985 , 0.14404357, 1.45427351, 0.76103773,
       0.12167502, 0.44386323, 0.33367433, 1.49407907, 0.3130677 ,
       0.6536186 , 0.8644362 , 2.26975462, 0.04575852])

In [38]:
data[data > 0] = 0  ##Для элементов со значением индекса True изменить значение на 0
data

array([[ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        , -0.97727788,  0.        , -0.15135721],
       [-0.10321885,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        , -0.20515826,  0.        , -0.85409574],
       [-2.55298982,  0.        ,  0.        , -0.74216502],
       [ 0.        , -1.45436567,  0.        , -0.18718385]])

In [30]:
data[colors != 'Green'] = 5
data

array([[ 5.        ,  5.        ,  5.        ,  5.        ],
       [ 0.        , -0.97727788,  0.        , -0.15135721],
       [ 5.        ,  5.        ,  5.        ,  5.        ],
       [ 5.        ,  5.        ,  5.        ,  5.        ],
       [ 5.        ,  5.        ,  5.        ,  5.        ],
       [-2.55298982,  0.        ,  0.        , -0.74216502],
       [ 0.        , -1.45436567,  0.        , -0.18718385]])

In [39]:
# Есть массив, нужно вывести элементы, согласно условию:
# 1.Вывести все элементы кратные 3
# 2.Вывести все элементы кратные 5
# 3.Вывести все элементы кратные и 3 и 5
# 4.Вывести все элементы кратные 3 или 5, кроме четных
# Подсказка: нужно использовать % или функцию astype()
np.random.seed(555)
vector = np.random.randint(1, 100, size=20)
vector

array([27, 47, 34, 69, 39, 23, 54, 97, 85, 23, 87, 54, 75, 86, 28, 93, 59,
        5, 66, 21])

In [40]:
mask_1 = (vector % 3 == 0)
vector[mask_1]

array([27, 69, 39, 54, 87, 54, 75, 93, 66, 21])

In [41]:
mask_2 = (vector % 5 == 0)
vector[mask_2]

array([85, 75,  5])

In [42]:
mask_3 = (vector % 3 == 0) & (vector % 5 == 0)  ## Используем логическое И
mask_3

array([False, False, False, False, False, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False])

In [43]:
vector[mask_3]

array([75])

In [44]:
mask_4 = (vector % 3 == 0) & (vector % 5 == 0) & (vector % 2 != 0)
vector[mask_4]

array([75])

In [45]:
mask_5 = ((vector % 3 == 0) | (vector % 5 == 0)) & (vector % 2 != 0)
vector[mask_5]

array([27, 69, 39, 85, 87, 75, 93,  5, 21])

#### Другой вариант решения

In [46]:
mask_6 = (vector % 3 == 0)
mask_6

array([ True, False, False,  True,  True, False,  True, False, False,
       False,  True,  True,  True, False, False,  True, False, False,
        True,  True])

In [59]:
~mask_6  ## Инверсия: True -> False, False -> True

array([False,  True,  True, False, False,  True, False,  True,  True,
        True, False, False, False,  True,  True, False,  True,  True,
       False, False])

In [57]:
vector % 3

array([0, 2, 1, 0, 0, 2, 0, 1, 1, 2, 0, 0, 0, 2, 1, 0, 2, 2, 0, 0],
      dtype=int32)

In [47]:
vector[~(vector % 3).astype(bool)]  # 0 -> False, все, что не нуль -> True

array([27, 69, 39, 54, 87, 54, 75, 93, 66, 21])

In [48]:
mask = (~(vector % 3).astype(bool) | ~(vector % 5).astype(bool))
mask

array([ True, False, False,  True,  True, False,  True, False,  True,
       False,  True,  True,  True, False, False,  True, False,  True,
        True,  True])

In [49]:
vector[mask]

array([27, 69, 39, 54, 85, 87, 54, 75, 93,  5, 66, 21])

### Добавление и удаление элементов

In [51]:
a1 = np.full((3, 5), 3)
a2 = np.arange(10).reshape(5, 2)

In [52]:
a1

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [53]:
a2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [56]:
a1 @ a2     # скалярное произведение

array([[60, 75],
       [60, 75],
       [60, 75]])

In [24]:
## Создание двух двумерных массивов с размерностями 9х1 и 1х4
x, y = np.ogrid[1:10, 1:5]

In [25]:
x

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [26]:
y

array([[1, 2, 3, 4]])

In [27]:
z = x * y
z

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16],
       [ 5, 10, 15, 20],
       [ 6, 12, 18, 24],
       [ 7, 14, 21, 28],
       [ 8, 16, 24, 32],
       [ 9, 18, 27, 36]])

In [28]:
## Копирует значения несколько раз и результат в виде flat массива
z.repeat(2)

array([ 1,  1,  2,  2,  3,  3,  4,  4,  2,  2,  4,  4,  6,  6,  8,  8,  3,
        3,  6,  6,  9,  9, 12, 12,  4,  4,  8,  8, 12, 12, 16, 16,  5,  5,
       10, 10, 15, 15, 20, 20,  6,  6, 12, 12, 18, 18, 24, 24,  7,  7, 14,
       14, 21, 21, 28, 28,  8,  8, 16, 16, 24, 24, 32, 32,  9,  9, 18, 18,
       27, 27, 36, 36])

In [57]:
mas3 = np.arange(20, 26).reshape(2, 3)
mas3

array([[20, 21, 22],
       [23, 24, 25]])

In [62]:
# Создает новый вектор или матрицу, увеличенные в нужное количество раз по каждой оси
np.tile(mas3, (3, 1))

array([[20, 21, 22],
       [23, 24, 25],
       [20, 21, 22],
       [23, 24, 25],
       [20, 21, 22],
       [23, 24, 25]])

In [64]:
zero_mas = np.zeros((8, 8))
zero_mas[::2,::2] = 1
zero_mas[1::2,1::2] = 1
zero_mas

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

In [65]:
np.tile(np.array([[0, 1], [1, 0]]), (4, 4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [66]:
np.tile(mas3, (3, 4))

array([[20, 21, 22, 20, 21, 22, 20, 21, 22, 20, 21, 22],
       [23, 24, 25, 23, 24, 25, 23, 24, 25, 23, 24, 25],
       [20, 21, 22, 20, 21, 22, 20, 21, 22, 20, 21, 22],
       [23, 24, 25, 23, 24, 25, 23, 24, 25, 23, 24, 25],
       [20, 21, 22, 20, 21, 22, 20, 21, 22, 20, 21, 22],
       [23, 24, 25, 23, 24, 25, 23, 24, 25, 23, 24, 25]])

In [ ]:
# Задача 2
# Дан массив, поменять знак у элементов, значения которых между 3 и 8

In [68]:
ex = np.arange(15).reshape(5, 3)
ex

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [69]:
mask_ex = (ex > 3) & (ex < 8)
mask_ex

array([[False, False, False],
       [False,  True,  True],
       [ True,  True, False],
       [False, False, False],
       [False, False, False]])

In [70]:
ex[mask_ex] *= -1  ## x = x * 1  -> x *= 1
ex

array([[ 0,  1,  2],
       [ 3, -4, -5],
       [-6, -7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Fancy indexing 

In [71]:
a = np.full((4, 8), np.arange(8))
a

array([[0, 1, 2, 3, 4, 5, 6, 7],
       [0, 1, 2, 3, 4, 5, 6, 7],
       [0, 1, 2, 3, 4, 5, 6, 7],
       [0, 1, 2, 3, 4, 5, 6, 7]])

In [72]:
a = a.T

In [73]:
a

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4],
       [5, 5, 5, 5],
       [6, 6, 6, 6],
       [7, 7, 7, 7]])

In [74]:
a[[4, 3, 0, 6]] ##Изменяем порядок выдачи строк с указанными индексами

array([[4, 4, 4, 4],
       [3, 3, 3, 3],
       [0, 0, 0, 0],
       [6, 6, 6, 6]])

In [75]:
a[[-3, -5, -7]]

array([[5, 5, 5, 5],
       [3, 3, 3, 3],
       [1, 1, 1, 1]])

In [76]:
a = np.arange(32).reshape((8, 4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [77]:
a[:, [-1, 1]]

array([[ 3,  1],
       [ 7,  5],
       [11,  9],
       [15, 13],
       [19, 17],
       [23, 21],
       [27, 25],
       [31, 29]])

#### Но здесь по-другому!!!

In [78]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [80]:
a[[1, 5, 7, 2], [0, 3, 1, 2]] # (1, 0), (5, 3), (7, 1), (2, 2) это индексы элементов

array([ 4, 23, 29, 10])

In [81]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [82]:
a[[1, 5, 7, 2]]

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23],
       [28, 29, 30, 31],
       [ 8,  9, 10, 11]])

In [117]:
## Работа с осями
a[np.ix_([1, 5, 7, 2], [0, 0, 3, 1, 2, 0])]

array([[ 4,  4,  7,  5,  6,  4],
       [20, 20, 23, 21, 22, 20],
       [28, 28, 31, 29, 30, 28],
       [ 8,  8, 11,  9, 10,  8]])

In [83]:
# Изменение порядка осей. В данном случае тоже самое, что и transpose()
a[np.ix_([1, 5, 7, 2], [0, 0, 3, 1, 2, 0])].swapaxes(1, 0) 

array([[ 4, 20, 28,  8],
       [ 4, 20, 28,  8],
       [ 7, 23, 31, 11],
       [ 5, 21, 29,  9],
       [ 6, 22, 30, 10],
       [ 4, 20, 28,  8]])

In [87]:
a = np.arange(16) ** 2
a = a.reshape(4, 4)
print(a)
print(a.ravel())
b = a.take([3, 5, 7, 15]) ## Индексы вектор-строки
b

[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]
 [144 169 196 225]]
[  0   1   4   9  16  25  36  49  64  81 100 121 144 169 196 225]


array([  9,  25,  49, 225], dtype=int32)

In [88]:
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121],
       [144, 169, 196, 225]], dtype=int32)

In [89]:
a.take([1, 13])

array([  1, 169], dtype=int32)

In [109]:
a

array([[  0,   1,  33,   9],
       [ 16,  25,  36,  49],
       [ 64,  81,  44, 121],
       [144, 169, 196, 225]], dtype=int32)

In [110]:
## Меняем значения у элементов с индексами 2 и 10
a.put([2, 10], [33, 44]); a   # Индексы вектор-строки

array([[  0,   1,  33,   9],
       [ 16,  25,  36,  49],
       [ 64,  81,  44, 121],
       [144, 169, 196, 225]], dtype=int32)

In [111]:
a2d = np.random.randint(50, size=[3, 5]); a2d

array([[20, 21,  2, 26, 17],
       [48, 32,  8, 48, 48],
       [42, 12, 41, 40, 25]])

In [112]:
a2d.shape

(3, 5)

In [113]:
a2d.put([0, 1 * 5 + 1, 2 * 5 + 2, 1 * 5 + 3, 4], [100, 101, 102, 103, 104]); a2d

array([[100,  21,   2,  26, 104],
       [ 48, 101,   8, 103,  48],
       [ 42,  12, 102,  40,  25]])

In [114]:
min_idx = np.argmin(a2d);min_idx ## Индекс минимального элемента массива-ленточки(flatten)

2

In [115]:
a2d.shape

(3, 5)

In [119]:
index = min_idx // a2d.shape[0], min_idx % a2d.shape[0]; index

(0, 2)

In [120]:
a2d[index]

2

In [121]:
## Изменяет значение линейного индекса в индекс нужной размерности
np.unravel_index(min_idx, a2d.shape)

(0, 2)

In [122]:
max_idx = np.argmax(a2d);max_idx  ## Индекс максимального элемента массива

4

In [123]:
np.unravel_index(max_idx, a2d.shape)

(0, 4)

In [124]:
min_idx = 11
min_idx

11

In [125]:
np.unravel_index(min_idx, (3, 3, 3)) ## Изменяет значение линейного индекса в индекс нужной размерности

(1, 0, 2)

In [126]:
a2d[np.unravel_index(max_idx, a2d.shape)] ## Максимальный элемент массива

104

In [83]:
np.unravel_index(max_idx, (3, 5)) # Индекс максимального элемент массива

(0, 4)

In [84]:
np.take(a2d, max_idx)  # тот же самый результат, но с помощью flat индекса

104

### numpy.where - это векторный вариант тернарного выражения x if condition else y

In [128]:
# 1 Вариант
if len('hello') > 4:
    print('good')
else:
    print('bad')

# 2 Вариант
print('good') if len('hello') > 4 else print('bad')
    
res = 'good line' if len('hello') > 5 else 'bad line'
print(res)

i = 5
result = i ** 2 if i > 4 else i ** 3
print(result)

good
good
bad line
25


In [129]:
x_array = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
y_array = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
condition = np.array([True, False, True, True, False])

In [130]:
list(zip(x_array, y_array, condition))

[(1.1, 2.1, True),
 (1.2, 2.2, False),
 (1.3, 2.3, True),
 (1.4, 2.4, True),
 (1.5, 2.5, False)]

In [131]:
result = [(x if c else y) for x, y, c in zip(x_array, y_array, condition)]
result

[1.1, 2.2, 1.3, 1.4, 2.5]

In [89]:
## Результат - это индексы, в которых значение True
np.where(condition)

(array([0, 2, 3], dtype=int64),)

In [133]:
# Если condition == True тогда берем элемент из x_array, иначе из y_array
result = np.where(condition, x_array, y_array)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [134]:
# Возращает индексы элементов, для которых верно условие
idx = np.where(x_array > 1.3); idx

(array([3, 4], dtype=int64),)

In [136]:
x_array[idx]

array([1.4, 1.5])

In [150]:
np.random.seed(5)
a = np.random.randn(4, 4); a

array([[ 0.44122749, -0.33087015,  2.43077119, -0.25209213],
       [ 0.10960984,  1.58248112, -0.9092324 , -0.59163666],
       [ 0.18760323, -0.32986996, -1.19276461, -0.20487651],
       [-0.35882895,  0.6034716 , -1.66478853, -0.70017904]])

In [151]:
np.where(a > 0, 2, -2) # положительные меняем на 2, отрицательные на -2

array([[ 2, -2,  2, -2],
       [ 2,  2, -2, -2],
       [ 2, -2, -2, -2],
       [-2,  2, -2, -2]])

In [154]:
np.where((a > -1) & ( a < 0), 99, a)  # Для чисел из интервала (-1;0) установим значение 99

array([ 0.44122749, 99.        ,  2.43077119, 99.        ])

In [155]:
np.where((a[0] > -1) & ( a[0] < 0), 99, a[0]) 

array([ 0.44122749, 99.        ,  2.43077119, 99.        ])

In [159]:
np.where((a[:, 0] > -1) & ( a[:, 0] < 0), 99, a[:, 0]) 

array([ 0.44122749,  0.10960984,  0.18760323, 99.        ])

In [ ]:
# Пример использования функции np.where()
# result = []
# for i in range(n):
#    if condition_1[i] and condition_2[i]:
#        result.append(0)
#    elif condition_1[i]:
#       result.append(1)
#    elif condition_2[i]:
#        result.append(2)
#    else:
#        result.append(3)

        
np.where(condition_1 & condition_2, 0, 
         np.where(condition_1, 1, 
                  np.where(condition_2, 2, 3)))
                